// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ExGwhGM_qA43hGWYDWDSrFBb9H-hbNg',
    appId: '1:446010431265:web:76e0200691ac0175815060',
    messagingSenderId: '446010431265',
    projectId: 'chat-app-3-989e9',
    authDomain: 'chat-app-3-989e9.firebaseapp.com',
    storageBucket: 'chat-app-3-989e9.appspot.com',
    measurementId: 'G-J9VQ846Z5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOje9VOuCTR1Yo2yo_QXAH7dAeSi4CPvQ',
    appId: '1:446010431265:android:f7da698335253067815060',
    messagingSenderId: '446010431265',
    projectId: 'chat-app-3-989e9',
    storageBucket: 'chat-app-3-989e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO25Jj8gHH7z2d0V2CaeEjaUMou7L0a-Y',
    appId: '1:446010431265:ios:d033dae81b10d31f815060',
    messagingSenderId: '446010431265',
    projectId: 'chat-app-3-989e9',
    storageBucket: 'chat-app-3-989e9.appspot.com',
    androidClientId: '446010431265-cul7hfium96s6fqq70ugoglbnurq0gkh.apps.googleusercontent.com',
    iosClientId: '446010431265-4n13vvir288558smj91mdh9lf6lv62md.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO25Jj8gHH7z2d0V2CaeEjaUMou7L0a-Y',
    appId: '1:446010431265:ios:e01055ce14e2b43c815060',
    messagingSenderId: '446010431265',
    projectId: 'chat-app-3-989e9',
    storageBucket: 'chat-app-3-989e9.appspot.com',
    androidClientId: '446010431265-cul7hfium96s6fqq70ugoglbnurq0gkh.apps.googleusercontent.com',
    iosClientId: '446010431265-ti8a4k9uuv2npstdr5cp28vi4ovkic52.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeData.RunnerTests',
  );
}
